networks:
  internal:
    driver: bridge

# Plex integration
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/plexpy:/config
      - /var/log/plexpy:/logs:ro
      - ${USERDIR}/docker/certs:/certs
    ports:
      - 8181:8181
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Media Management
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/certs:/certs
      - /mnt:/media
    ports:
      - 9117:9117
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# TV Show Management
  sonarr:
    # build: /etc/environment
    #image: linuxserver/sonarr:latest
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    volumes:
      - /opt/appdata/sma:/usr/local/sma/config
      - ${USERDIR}/docker/sonarr:/config
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/certs:/certs
      - "/mnt/plex1/plex/tv shows:/tv"
      - /mnt:/media
    ports:
        - 8989:8989
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Movie Management
  radarr:
    # build: /etc/environment
    #image: linuxserver/radarr:latest
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - /opt/appdata/sma:/usr/local/sma/config
      - ${USERDIR}/docker/radarr:/config
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/certs:/certs
      - "/mnt/plex1/plex/tv shows:/tv"
      - /mnt:/media
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

# Media Request Management
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/overseer/config:/app/config
      - /mnt:/media
    ports:
      - 5055:5055
    restart: unless-stopped

# Media Indexing
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/prowlarr:/config
      - /mnt:/media
    ports:
      - 9696:9696
    restart: unless-stopped
    
# Homepage/Dashboard
  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    ports:
      - 7575:7575

# Captcha Solver
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8191:8191

# User Request Hub
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - /mnt/plex/books:/books # Default destination for book downloads
      - ${USERDIR}/docker/shelfmark/config:/config # App configuration
      - /mnt/plex/torrent-complete:/downloads

# Main Library DB & Backend Ingestion Engine
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD} # Optional, set a password for the VNC server
    volumes:
      - ${USERDIR}/docker/calibre/config:/config
      - /mnt/plex/books:/books      # Shared Library Directory
      - ${USERDIR}/docker/calibre/import:/auto_add    # Map directly to Bindery's output folder
    ports:
      - 8080:8080 # Http VNC Desktop View
      - 8081:8081 # Content Server
      - 8082:8181 # HTTPS VNC Desktop View
    shm_size: '1gb'

# User Reading & UI Frontend
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mod:calibre-web-kepubify # Auto Kobo formatting
    volumes:
      - ${USERDIR}/docker/calibre-web/config:/config
      - /mnt/plex/books:/books      # Must match Calibre's main storage exactly
    ports:
      - 8083:8083
    depends_on:
      - calibre

volumes:
  postgres_data:
  redis_data: